apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eth-indexer.fullname" . }}-config
data: 
  NODE_ENV: "production"

  #postgres config:
  POSTGRES_HOST: "blockchain-dev-postgres.blockchain-dev.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: ""
  POSTGRES_DATABASE: "ethereum"

  #worker config:
  RETRY_FIND_WORKER_DELAY: "1000" #ms
  RETRY_FIND_WORKER_COUNT: "10000"

  #db query config:
  MAX_RETRIES: "10"
  RETRY_DELAY: "10000"

  #eth config:
  ETH_WS_URL: "wss://ws.dev.hydrasquare-holding.com"
  BLOCK_EXPLORER_URL: "https://blockscout.dev.hydrasquare-holding.com"
  BLOCK_EXPLORER_API_KEY: "08f713f8-5626-4c89-b0a7-07ea6acc1521"

  #log config:
  LOG_LEVEL: "notice"
  #Levels:
  #   emerg: 0,
  #   alert: 1,
  #   crit: 2,
  #   error: 3,
  #   warning: 4,
  #   notice: 5,
  #   info: 6,
  #   debug: 7