apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eth-indexer.fullname" . }}-config
data: 
    ETH_INDEXER: "production"
    VERSION: "1.0"
    LOG_LEVEL: "warn" #info, warn, debug, error

    HTTP_RPC_ENDPOINT: "https://rpc.dev.bcf-lab.com"
    WS_RPC_ENDPOINT: "wss://ws.dev.bcf-lab.com"

    POSTGRES_HOST: "web3-postgres.web3.svc.cluster.local"
    POSTGRES_PORT: "5432"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: ""
    POSTGRES_DATABASE: "ethereum"
    POSTGRES_CREATE_TABLE_ORDER: "config,blocks,transactions,transactions_receipts,addresses,contracts,tokens,token_transfers,logs"

    BATCH_SIZE: "500" # above 500 the blocks per second drops
    START_BLOCK: "0"
    END_BLOCK: "-1"

    BLOCKSCOUT_ENDPOINT: "https://blockscout.dev.bcf-lab.com"
    BLOCKSCOUT_API_KEY: "6dc17aa2-3362-4e15-a2b4-704b0682e052"